### ISSUE TITLE
Chihaya doesn't seem to share peers between clients

### ISSUE THREAD

**Issue by ptdel** [chihaya/chihaya#347]
running v2.0.0.0-rc.2 out of docker with "host" network mode.
```
chihaya:
  announce_interval: 15m
  prometheus_addr: 0.0.0.0:6880
  max_numwant: 100
  default_numwant: 25
  max_scrape_infohashes: 50

  http:
    addr: 0.0.0.0:6881
    allow_ip_spoofing: true
    real_ip_header: X-Real-IP
    read_timeout: 5s
    write_timeout: 5s
    request_timeout: 5s

  storage:
    name: memory
    config:
      gc_interval: 14m
      peer_lifetime: 16m
      shards: 1024
      prometheus_reporting_interval: 1s
```
I don't seem to pass any peers to clients (I don't know if I'm even retaining peer info).  Going by what I can see if I decode /scrape responses and using the `poke` utility I found referenced in another issue here:

```
2017/07/09 16:36:26 Response: [d8:intervali900e12:min intervali900e5:peers6:    8:completei0e10:incompletei1ee]
Tracker supports HTTP compact announces: true
Tracker supports HTTP non-compact announces: true
Tracker supports IP spoofing: false
Tracker supports optimized announce responses: false
Tracker supports optimized seeder announce responses: true

Poke ran these tests:

Test: trackerSupportsCompactAnnounce
Result: true

Test: trackerSupportsNonCompactAnnounce
Result: true

Test: trackerSupportsAnnouncingPeerNotInPeerListAnnounce
Result: false

Test: trackerSupportsIPSpoofingAnnounce
Result: false
Error: announce of second peer returned unknown peer

Test: trackerSupportsOptimizedSeederResponseAnnounce
Result: true

Test: basicAnnounce

Poke did not run these tests:
```
I'll admit I'm still familiarizing myself with the code base, so the real issue here may be that I'm dense.  I ran through each struct corresponding to the config file and didn't see any extra yaml fields that I might be missing for peer info

nothing in stdout when running chihaya seems to indicate an issue with storage, on the contrary it appears to provision just fine and reporting for it in prometheus seems fine.
