### ISSUE TITLE
The udp protocol's tracer server appears error code [bad connection ID]

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#417]
The udp protocol's tracer server appears error code [bad connection ID]
![image](https://user-images.githubusercontent.com/19538878/45584536-f4eecb00-b907-11e8-84d0-51a2bdb42402.png)

`udp://37.1.210.233:80/announce`   Serving chihaya，Unfortunately, he has made a mistake.

`udp://ipv4.opentracker.xyz:80/announce`  is [opentracker](http://erdgeist.org/arts/software/opentracker/)
Opentracker is normal.

please

**Comment by f4nff** [comment]
After many tests, it was normal to change the port. I switched to port 443.

**Comment by jzelinskie** [comment]
What client are you using? Chihaya uses a different strategy for managing connection IDs than OpenTracker, but it strictly follows the specification (BEP15). It's quite possible the client is not actually respecting the standard as it's defined.

**Comment by f4nff** [comment]
> uTorrent Stable (3.5.0 build 43580)

**Comment by mrd0ll4r** [comment]
Hey,

did you restart chihaya while the client was connected?

Also, can you please provide a wireshark dump of the connection, from the client's perspective? If you want, you can also provide chihaya debug logs, but it appears your tracker is running in production, so they might pretty big.

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/45595742-ceea2900-b9e2-11e8-82ab-8c01ab0d1b03.png)

**Comment by f4nff** [comment]
1：download [utorrent](https://filehippo.com/zh/download_utorrent/74384/)
2：start chihaya tracker.

>  chihaya --config  chihaya.yaml

chihaya.yaml txt

```
chihaya:
  # The interval communicated with BitTorrent clients informing them how
  # frequently they should announce in between client events.
  announce_interval: 5m

  # The interval communicated with BitTorrent clients informing them of the
  # minimal duration between announces.
  min_announce_interval: 5m

  # The network interface that will bind to an HTTP endpoint that can be
  # scraped by an instance of the Prometheus time series database.
  # For more info see: https://prometheus.io
  prometheus_addr: "0.0.0.0:6880"

  # The maximum number of peers returned in an announce.
  max_numwant: 50

  # The default number of peers returned in an announce.
  default_numwant: 25

  # The number of infohashes a single scrape can request before being truncated.
  max_scrape_infohashes: 50

  # This block defines configuration for the tracker's HTTP interface.
  # If you do not wish to run this, delete this section.
  http:
    # The network interface that will bind to an HTTP server for serving
    # BitTorrent traffic. Remove this to disable the non-TLS listener.
    addr: "0.0.0.0:810"

    # The network interface that will bind to an HTTPS server for serving
    # BitTorrent traffic. If set, tls_cert_path and tls_key_path are required.
    https_addr: ""

    # The path to the required files to listen via HTTPS.
    tls_cert_path: ""
    tls_key_path: ""

    # The timeout durations for HTTP requests.
    read_timeout: 5s
    write_timeout: 5s

    # When true, persistent connections will be allowed. Generally this is not
    # useful for a public tracker, but helps performance in some cases (use of
    # a reverse proxy, or when there are few clients issuing many requests).
    enable_keepalive: false
    idle_timeout: 30s

    # Whether to time requests.
    # Disabling this should increase performance/decrease load.
    enable_request_timing: false

    # Whether to listen on /announce.php and /scrape.php in addition to their
    # non-.php counterparts.
    # This is an option for compatibility with (very) old clients or otherwise
    # outdated systems.
    # This might be useful to retracker.local users, for more information see
    # http://rutracker.wiki/Оптимизация_обмена_битторрент_траффиком_в_локальных_сетях
    # and
    # http://rutracker.wiki/Retracker.local
    enable_legacy_php_urls: false

    # When enabled, the IP address used to connect to the tracker will not
    # override the value clients advertise as their IP address.
    allow_ip_spoofing: false

    # The HTTP Header containing the IP address of the client.
    # This is only necessary if using a reverse proxy.
    real_ip_header: "X-Forwarded-For"

    # The maximum number of peers returned for an individual request.
    max_numwant: 100

    # The default number of peers returned for an individual request.
    default_numwant: 50

    # The maximum number of infohashes that can be scraped in one request.
    max_scrape_infohashes: 50

  # This block defines configuration for the tracker's UDP interface.
  # If you do not wish to run this, delete this section.
  udp:
    # The network interface that will bind to a UDP server for serving
    # BitTorrent traffic.
    addr: "0.0.0.0:80"

    # The leeway for a timestamp on a connection ID.
    max_clock_skew: 10s

    # The key used to encrypt connection IDs.
    private_key: "paste a random string here that will be used to hmac connection IDs"

    # Whether to time requests.
    # Disabling this should increase performance/decrease load.
    enable_request_timing: false

    # When enabled, the IP address used to connect to the tracker will not
    # override the value clients advertise as their IP address.
    allow_ip_spoofing: false

    # The maximum number of peers returned for an individual request.
    max_numwant: 100

    # The default number of peers returned for an individual request.
    default_numwant: 50

    # The maximum number of infohashes that can be scraped in one request.
    max_scrape_infohashes: 50


  # This block defines configuration used for the storage of peer data.
  storage:
    name: memory
    config:
      # The frequency which stale peers are removed.
      gc_interval: 3m

      # The amount of time until a peer is considered stale.
      # To avoid churn, keep this slightly larger than `announce_interval`
      peer_lifetime: 31m

      # The number of partitions data will be divided into in order to provide a
      # higher degree of parallelism.
      shard_count: 1024

      # The interval at which metrics about the number of infohashes and peers
      # are collected and posted to Prometheus.
      prometheus_reporting_interval: 1s

  # This block defines configuration used for middleware executed before a
  # response has been returned to a BitTorrent client.
  prehooks:
  #- name: jwt
  #  options:
  #    issuer: "https://issuer.com"
  #    audience: "https://chihaya.issuer.com"
  #    jwk_set_url: "https://issuer.com/keys"
  #    jwk_set_update_interval: 5m

  #- name: client approval
  #  options:
  #    whitelist:
  #    - "OP1011"
  #    blacklist:
  #    - "OP1012"

  #- name: interval variation
  #  options:
  #    modify_response_probability: 0.2
  #    max_increase_delta: 60
  #    modify_min_interval: true
```

3: start µTorrent
4:Just find a seed to [download ](http://releases.ubuntu.com/16.04/ubuntu-16.04.5-server-amd64.iso.torrent)
5：Pause the task and then delete the tracker server inside the seed, all.
6：Add a local tracker server `udp://127.0.0.1:80/announce`
7:Waiting all the time, after about 30 minutes, an exception will occur.
