### ISSUE TITLE
The program takes up very little memory

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#418]
The program takes up very little memory，Can it be optimized?
Compared with [opentracker](https://erdgeist.org/arts/software/opentracker/), the performance is quite different.

![ram](https://user-images.githubusercontent.com/19538878/45600415-efd86b80-ba2e-11e8-8d3c-3d21e0e72d68.png)

Multiple programs have been killed by the system。

**Comment by f4nff** [comment]
At present, the number of visits is small, and the pressure is already high. Can the author optimize the efficiency of the code? If not, it requires a high hardware configuration to run.

**Comment by mrd0ll4r** [comment]
Hey,
use https://github.com/mrd0ll4r/chihaya-optmem-peerstore as the storage implementation, it'll save memory. Uses a little bit more CPU, but not much.

**Comment by f4nff** [comment]
Is there a complete project? I don't know how to import, I am a rookie.

**Comment by mrd0ll4r** [comment]
Alright, you need to add one import statement in 'cmd/chihaya/config.go`:

```go
...
    // Imported to register as storage drivers.
    _ "github.com/chihaya/chihaya/storage/memory"
    _ "github.com/chihaya/chihaya/storage/memorybysubnet"
    _ "github.com/mrd0ll4r/chihaya-optmem-peerstore/optmem"
...
```

And then in your configuration replace the storage block with:
```yaml
  storage:
    name: optmem
    config:
      shard_count_bits: 10
      gc_interval: 2m
      peer_lifetime: 16m
      prometheus_reporting_interval: 1s
```

I just updated the optmem repository yesterday, you might have to git pull. Let me know how it works! :)
